### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [mmontone/mutils#1]
Building with SBCL 2.3.6.173-55d27b14b / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 70f1ce8f13e609ea8a6ff3f0a6cbe7e46640880b

*mutils* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Package PPCRE does not exist. Line: 31, Column: 66, File-Position: 1001 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/mutils/a69a17f1d8a4faa6551649cb06e1de9107e3c2a8/mutils-20230727-git/mutils.lisp" {1004C4DD13}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD tid=2325366 "main thread" RUNNING {1001710003}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "mutils" "mutils">

```

[Full log here](http://report.quicklisp.org/2023-07-27/failure-report/mutils.html)

**Comment by mmontone** [comment]
Apologies for having made this more difficult than needed.
My SLIME is contaminated with lots of pre-loaded dependencies, so I didn't see the dependency error.
This is solved now.
